live_config_reload = true

import = [
    # uncomment the flavour you want below:
    #~/.config/alacritty/catppuccin-latte.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    "~/.config/alacritty/catppuccin-macchiato.toml"
    #"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.75
blur = true
# [window.padding]
# x = 5 
# y = 5 


[font]
size = 10.0

[font.bold]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Bold"
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold"

[font.bold_italic]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Bold Italic"
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold Italic"

[font.italic]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Italic"
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.normal]
# family = "JetBrainsMono Nerd Font Mono"
# style = "regular"
family = "JetBrainsMono Nerd Font Mono"
style = "demibold"


